version: "3.6"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    restart: unless_stopped
    volumes:
      - test_api_data_mongo:/data/db
  postgres-user:
    image: postgres
    environment:
      - POSTGRES_USER=api42
      - POSTGRES_PASSWORD=jean1904
      - POSTGRES_MULTIPLE_DATABASES="api_42Bets","42apiBets_testing"
    volumes:
      - ./docker-utils:/docker-entrypoint-initdb.d
      - test_api_data:/data/postgres
    ports:
      - 5432:5432
    restart: unless_stopped
    container_name: postgres

  app:
    container_name: 42ch-front
    build: .
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - JWT_ACCESS_SECRET=d5c6be5ea6f55fed6f9247d66df26543e733f9c180bac042849205820b725ac4
      - FORTY_TWO_CLIENT_SECRET=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
      - FORTY_TWO_CLIENT_ID=u-s4t2ud-3c1fad8697f8326af9434fb8146ff1101367143e885927ea3b5c0f94ec78065b
    restart: unless_stopped

  backend:
    container_name: 42ch-back
    build: backend/Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - mongo
      - postgres-user
    environment:
      - JWT_ACCESS_SECRET=d5c6be5ea6f55fed6f9247d66df26543e733f9c180bac042849205820b725ac4
      - FORTY_TWO_CLIENT_SECRET=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
      - FORTY_TWO_CLIENT_ID=u-s4t2ud-3c1fad8697f8326af9434fb8146ff1101367143e885927ea3b5c0f94ec78065b
    restart: unless_stopped

volumes:
  test_api_data: {}
  test_api_data_mongo: {}
